const types = {
    FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
    FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    SUBMIT_TODO: 'SUBMIT_TODO',
    DELETE_TODO: 'DELETE_TODO'
};

export default types
