const types = {
    FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
    FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    SUBMIT_TODO: 'SUBMIT_TODO',
    SUBMIT_TODO_FAILURE: 'SUBMIT_TODO_FAILURE',
    SUBMIT_TODO_SUCCESS: 'SUBMIT_TODO_SUCCESS',
    EDIT_TODO: 'EDIT_TODO',
    EDIT_TODO_FAILURE: 'EDIT_TODO_FAILURE',
    EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
    DELETE_TODO: 'DELETE_TODO',
    DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS'
};

export default types
